# Generated by Django 5.2.1 on 2025-05-21 18:07

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_is_active', models.BooleanField(default=False)),
                ('balance', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('reference', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=12, primary_key=True, serialize=False, unique=True, uppercase=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('verified', 'verified'), ('pending', 'pending')], max_length=255)),
                ('proof', models.ImageField(blank=True, null=True, upload_to='')),
                ('completed', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('card', models.CharField(max_length=255)),
                ('expiring_date', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=4)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.profile')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('bank_location', models.TextField()),
                ('swiss_code', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=12, primary_key=True, serialize=False, unique=True, uppercase=True)),
                ('amount', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('ongoing', 'ongoing'), ('closed', 'closed')], max_length=255)),
                ('conclusion', models.CharField(choices=[('profit', 'profit'), ('loss', 'loss'), ('pending', 'pending')], max_length=255)),
                ('duration', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profit_margin', models.FloatField(default=7.5)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('reference', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=12, primary_key=True, serialize=False, unique=True, uppercase=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('amount', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('signup', 'Signup Bonus'), ('referal', 'Referal Bonus'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=255)),
                ('method', models.CharField()),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('reference', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=12, primary_key=True, serialize=False, unique=True, uppercase=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('verified', 'verified'), ('pending', 'pending')], max_length=255)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.bankaccount')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.profile')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.wallet')),
            ],
        ),
    ]
