# Generated by Django 5.2.1 on 2025-05-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('verified', 'verified'), ('pending', 'pending')], default='pending', max_length=255),
        ),
    ]
