# Generated by Django 5.2.1 on 2025-05-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_deposit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('verified', 'verified'), ('pending', 'pending')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('verified', 'verified'), ('pending', 'pending')], default='pending', max_length=255),
        ),
    ]
