# Generated by Django 5.2.1 on 2025-05-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_transaction_status_alter_withdrawal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
