# Generated by Django 5.2.1 on 2025-05-24 09:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_withdrawal_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='proof',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='proof',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
