# Generated by Django 5.2.1 on 2025-05-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_deposit_proof_alter_withdrawal_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='wallet_type',
            field=models.CharField(choices=[('btc', 'btc'), ('usdt', 'usdt'), ('eth', 'eth')], default='usdt', max_length=255),
        ),
    ]
