# Generated by Django 5.2.1 on 2025-05-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_deposit_wallet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='wallet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
